services:
  - type: web
    name: fitbase-backend-nest
    env: node
    rootDir: apps/backend-nest
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3200
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: fitbase-frontend-next
    env: node
    rootDir: apps/frontend-next
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_SITE_URL
        sync: false
      - key: NEXT_PUBLIC_LEGACY_SITE_URL
        sync: false
      - key: BACKEND_URL
        sync: false
